### ISSUE TITLE
error while running the code

### ISSUE THREAD

**Issue by 18211a05a0** [llopen-sourcell/Video-Steganography#5]
Hey
We are facing some issues while running this code. We are using python 3.8.2 version .
Can you please help us out in figuring these errors
[INFO] tmp directory is created
Traceback (most recent call last):
  File "C:/Users/ujwal/AppData/Local/Programs/Python/Python38/videostg.py", line 86, in <module>
    main()
  File "C:/Users/ujwal/AppData/Local/Programs/Python/Python38/videostg.py", line 73, in main
    call(["ffmpeg", "-i",f_name, "-q:a", "0", "-map", "a", "tmp/audio.mp3", "-y"],stdout=open(os.devnull, "w"), stderr=STDOUT)
  File "C:\Users\ujwal\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\ujwal\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\ujwal\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
>>>

**Comment by tuonglv00** [comment]
change the code into
call(["ffmpeg", "-i", f_name, "-q:a", "0", "-map", "a", "tmp/audio.mp3", "-y"], stdout=open(os.devnull, "w"),
         stderr=STDOUT, shell=True)
call(["ffmpeg", "-i", "tmp/%d.png", "-vcodec", "png", "tmp/video.mov", "-y"], stdout=open(os.devnull, "w"),
         stderr=STDOUT, shell=True)
call(["ffmpeg", "-i", "tmp/video.mov", "-i", "tmp/audio.mp3", "-codec", "copy", "video.mov", "-y"],
         stdout=open(os.devnull, "w"), stderr=STDOUT, shell=True)

**Comment by 18211a05a0** [comment]
Yes it's working perfectly thanks for responding. 
But the problem is this program split the video into frames and embed the message in it but after the embedding process it's not convert in to stego video file or embedded video format . My doubt is how to reveal message from it . If it is stored in temp files in frames

**Comment by KerinPithawala** [comment]
Same problem

**Comment by kekovina** [comment]
run with administrator rights
works for me
